name: Deploy AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Required to read repository contents

env:
   RESOURCE_GROUP: myResourceGroup
   AKS_CLUSTER_NAME: myAKSCluster
   LOCATION: australiaeast

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Set up Kubernetes tools
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    - name: Create Resource Group
      run: |
        az group create --name $RESOURCE_GROUP --location $LOCATION

    - name: Create AKS Cluster
      run: |
        az aks create --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME --node-count 1 --enable-addons monitoring --generate-ssh-keys

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yml
